### ISSUE TITLE
Error at extension loading

### ISSUE THREAD

**Issue by Miguel-Fontes** [siegebell/vsc-prettify-symbols-mode#16]
The extension isn't loading at my system, returning an 'undefined' error at load.

I've cloned your repo and took a shot running it at developer mode (F5).

Errors happened again but i could detect the cause.  The file name at [document.ts](https://github.com/siegebell/vsc-prettify-symbols-mode/blob/master/src/document.ts#L5) imports, at line 5 and 6 are written in camel case when the file name is all lower case.

I've changed that and now everything works fine. I don't know if someone else experienced the same thing.

I'm running vscode at a Ubuntu 16.04 LTS system.

Before:
![error-2016-12-15 22-45-59](https://cloud.githubusercontent.com/assets/15656072/21247716/e5bd1736-c318-11e6-8101-ad473a370801.png)

After:
![solution-2016-12-15 22-48-51](https://cloud.githubusercontent.com/assets/15656072/21247719/e8639d16-c318-11e6-80b7-06501f45fd74.png)

**Comment by siegebell** [comment]
..and git silently does not pick up on me renaming the case of file on Windows by default :/

Thanks for the report!

**Comment by siegebell** [comment]
@Miguel-Fontes I've got the patch ready to go; would you mind testing it before I publish by installing [prettify-symbols-mode-0.3.1.vsix](https://github.com/siegebell/vsc-prettify-symbols-mode/releases/tag/v0.3.1)? ([Refer here for instructions](https://code.visualstudio.com/Docs/extensions/install-extension#_install-a-packaged-extension-vsix).)

Thanks!

**Comment by Miguel-Fontes** [comment]
@siegebell had no success (same error) but i think the problem is the vsix file. 

You changed the filename to Uppercase on master branch, fixing the problem (tested). When i install via vsix, the error repeats. I've inspected the files at .vscode/extensions/, and looks like they're from the previous version - take a look below:

![build-3-1-vsix-2016-12-16 10-16-12](https://cloud.githubusercontent.com/assets/15656072/21262511/cbf1b022-c378-11e6-8fbc-a353b394b68a.png)

Can you rebuild it?

**Comment by siegebell** [comment]
@Miguel-Fontes fixed?

**Comment by Miguel-Fontes** [comment]
@siegebell Yes! Ship it!

**Comment by siegebell** [comment]
Published. Thanks for your help!

**Comment by Miguel-Fontes** [comment]
Hey, no problem. Thanks for this great extension!
