### ISSUE TITLE
Gigantic Text When Code is Folded?

### ISSUE THREAD

**Issue by alexhulbert** [siegebell/vsc-prettify-symbols-mode#28]
Hi! I really wanted to use your extension, but I can't because of a pretty big bug with the latest version of VSCode.

Let's say I have a bit of example code that looks like this: 
![Example Code](http://imgur.com/2UpvkPq.png)

If I try to fold the outermost if statement, this happens:  
![Gigantic Greater Than or Equal to Symbol](http://imgur.com/u9xeK61.png)

If I have any prettified symbol (in this case the >= symbol) in folded or collapsed code, it gets really big and shows itself like the above picture.

**Comment by siegebell** [comment]
Caused by #34.

**Comment by siegebell** [comment]
Fixed in release 0.4.1
