### ISSUE TITLE
[Question] Is it possible to reference matched ugly string in the pretty version?

### ISSUE THREAD

**Issue by JoeyEremondi** [siegebell/vsc-prettify-symbols-mode#31]
I'm wondering, is it possible to reference the matched ugly string in the Pretty version?

I have two use-cases (both Ott related):

* For any strings `X` and `n`, I'd like to be able to render `</ X // n />` with an overline over `X , and `n` superscript beside it
* For any greek letter followed by a number or a predetermined index variable (i.e. `i, j, k, m, n`), I'd like to make the number subscript

Both of these could be achieved if we could refer to parts of the matching string in the ugly version when specifying the pretty. 

Is such a thing possible with this library? Is there a reference for the regular expression format used? Or is there another way to achieve the types of things I'm doing?

**Comment by siegebell** [comment]
Sorry, that's currently not possible. And in general, not something I can support for performance reasons (vscode cannot handle too many individualized decorations).

**Comment by siegebell** [comment]
Would something like this work for you?
```
{ "ugly": "\\s*//\\s*1", "pretty": "¹", "pre": "\\b", "post": "\\b"},
{ "ugly": "X", "pre": "\\b", "post": "\\s*\\s*//", "style": {"hackCSS": "border-top: 1pt solid"}},
```

The basic idea is that you can substitute the superscript/subscript portion without touching "X", and then separately style "X" when you detect a superscript/subscript.
