### ISSUE TITLE
Problem with |> FiraCode ligature

### ISSUE THREAD

**Issue by windpeoples** [siegebell/vsc-prettify-symbols-mode#39]
Everything works well for me in F# with one exception, the FiraCode |> ligature is broken by the following:

> { "ugly": "\\|", "pretty": "║", "pre": "^\\s+" }

Unfortunately, it is being applied by default (it is NOT in my settings.json file, at least not that I can find). Is there a way to turn that particular substitution off? If not, could it at least be modified so it does not happen when the character after "|" is not ">"?

I tried overriding the behaviour using:

> { "ugly": "\\|", "pretty": "\\|", "pre": "^\\s+" }

but it did not work.

Thanks!

**Comment by siegebell** [comment]
You can change the behavior by specifying`"prettifySymbolsMode.substitutions"` in your vscode settings. Unfortunately, this will require you to copy the entire default setting in addition to your changes.

**Comment by windpeoples** [comment]
Thanks, will do!
