### ISSUE TITLE
How to pretty F# pipe? ( |> and <| )

### ISSUE THREAD

**Issue by hmua** [siegebell/vsc-prettify-symbols-mode#49]
Tried
```
{ "ugly": "|>","pretty": " ▷"},
{ "ugly": "<|","pretty": "◁ "},
```
and not working?

**Comment by artemisart** [comment]
@hmua You need to escape the | (it's a regex or), try "ugly": "\\|>".

**Comment by hmua** [comment]
@artemisart Thank you! I used `"ugly": "\\|>","pretty": "▷"` and it worked!
